export const WEBVIEW_ADD_URL = 'WEBVIEW_ADD_URL'
export const WEBVIEW_SELECT_URL = 'WEBVIEW_SELECT_URL'
export const WEBVIEW_REMOVE_URL = 'WEBVIEW_REMOVE_URL'
export const WEBVIEW_RELOAD_URL = 'WEBVIEW_RELOAD_URL'
export const WEBVIEW_BACK_URL = 'WEBVIEW_BACK_URL'
export const WEBVIEW_FORWARD_URL = 'WEBVIEW_FORWARD_URL'
export const WEBVIEW_LOAD_URL = 'WEBVIEW_LOAD_URL'
export const WEBVIEW_FINISH_LOAD = 'WEBVIEW_FINISH_LOAD' 
export const WEBVIEW_FAVICON_FLASH = 'WEBVIEW_FAVICON_FLASH' 
export const WEBVIEW_OPEN_SUPER = 'WEBVIEW_OPEN_SUPER' 
export const WEBVIEW_OPEN_URL = 'WEBVIEW_OPEN_URL'  

export const favorites_INIT = 'favorites_INIT'
export const favorites_ADD = 'favorites_ADD'
export const favorites_DELETE = 'favorites_DELETE' 
export const favorites_click = 'favorites_click'

